# @format

version: '3.8'
# delete this if no database is needed
volumes:
    db-data:
services:
    # delete this if no database is needed
    database:
        container_name: database
        # select the database image
        image: <database-image>
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            - PASS=${DB_AUTH}
            - USER=${DB_USER}
        volumes:
            - db-data:/data/db
        command: start
    app:
        build:
            context: .
            target: dev
        environment:
            - NODE_ENV=development
            - PORT=3000
            - DB_CONNECT=surrealdb
        ports:
            - ${PORT}:3000
        working_dir: /root/app
        volumes:
            - .:/root/app:chached
        restart: always
        command:
            - /bin/sh
            - -c
            - |
                yarn install
                yarn build
                yarn dev & yarn serve
