# @format

version: '3.8'
volumes:
    db-data:
services:
    # delete this if no database is needed
    database:
        container_name: database
        # select the database image
        image: <database-image>
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            - PASS=${DB_AUTH}
            - USER=${DB_USER}
        volumes:
            - db-data:/data/db
        command: start
    app:
        container_name: ${APP_NAME}
        image: ${APP_NAME}:${APP_TAG}
        restart: always
        environment:
            - PORT=${PORT}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_AUTH=${DB_AUTH}
        ports:
            - ${PORT}:3000
