# @format
# If no database is needed, you can safely delete this file

version: '3.8'
volumes:
    db-data:
services:
    # delete this if no database is needed
    database:
        container_name: database
        # select the database image
        image: <database-image>
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            - PASS=${DB_AUTH}
            - USER=${DB_USER}
        volumes:
            - db-data:/data/db
        command: start
