# @format

version: '3.8'
volumes:
    surreal-data:
services:
    surrealdb:
        container_name: surrealdb
        image: surrealdb/surrealdb:latest
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            - PASS=${DB_AUTH}
            - USER=${DB_USER}
        volumes:
            - surreal-data:/data/db
        command: start
    app:
        container_name: ${APP_NAME}
        image: ${APP_NAME}:${APP_TAG}
        restart: always
        environment:
            - PORT=${PORT}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_AUTH=${DB_AUTH}
            - DB_CONNECT=surrealdb
        ports:
            - ${PORT}:3000
